### ISSUE TITLE
Onkyo Receiver Support?

### ISSUE THREAD

**Issue by jhoff80** [bentemple/nvidia_shield_tv_controller#1]
Like discussed on Reddit, I've got an Onkyo receiver that I'd love to control via this.

The eISCP control you suggested works fine.  My specific model receiver is the TX-NR797.

The sources I use and switch between:

Nintendo Switch on Game.  eISCP command that worked was:
receiver.command('source game')

Xbox One on BD/DVD.  eISCP:
receiver.command('source bd')

Gaming PC on PC.  eISCP:
receiver.command('source pc')

ShieldTV connected to Stream Box.  eISCP:
receiver.command('source strm-box')

**Comment by bentemple** [comment]
Awesome! Thanks @jhoff80 I'll work on getting something setup this week or weekend and get back to you when I have something :) . If the eISCP utility works, this should be relatively painless. and since it does 🎉

**Comment by jhoff80** [comment]
Sounds great.  If it gets to be too much work, no big deal, but it'd be awesome if it's fairly simple to make work.

**Comment by bentemple** [comment]
If you can integrate your Onkyo receiver with Home Assistant, I recently added support to also send events to HA, which would allow you do what you need here.
Maybe: https://www.home-assistant.io/integrations/onkyo/
