### ISSUE TITLE
Samsung TV support

### ISSUE THREAD

**Issue by erousr** [bentemple/nvidia_shield_tv_controller#4]
Hi, 

I played around with your app trying to get this working on my Shield (2015) paired with Samsung UE65KS9500 and I managed to update your code to be able to send the correct code to the TV but failed to get a response.

After some investigation it seems Samsung uses some kind of tokens when communicating through web-socket. 

You can see how far I got here: https://github.com/erousr/nvidia_shield_tv_controller/commits/master

To work with newer Samsung TVs, a token authorization would have to be implemented. Here is a working project using tokens for Samsung: https://github.com/xchwarze/samsung-tv-ws-api/blob/master/README.md

Here is a thread explaining the token issue and solution more in detail: https://github.com/Ape/samsungctl/issues/114#issuecomment-529202420

Hopefully someone with more skills then me can bring this beautiful project forward for Samsung TVs too :)

I would gladly be test-pilot.

**Comment by bentemple** [comment]
Is there a Home assistant integration for your samsung TV?

**Comment by bentemple** [comment]
I would recommend using the following integration with Home Assistant, and setting up the Home Assistant version of this application. https://www.home-assistant.io/integrations/samsungtv/
